Update principalFlow.yml

diff --git a/.github/workflows/principalFlow.yml b/.github/workflows/principalFlow.yml
--- a/.github/workflows/principalFlow.yml
+++ b/.github/workflows/principalFlow.yml
@@ -47,12 +47,14 @@ jobs:
             USERNAME=$(echo "$DECODED_SECRET" | jq -r '.result.authFields.username')
             echo "Username is: $USERNAME"
             INSTANCE_URL=$(echo "$DECODED_SECRET" | jq -r '.result.authFields.instanceUrl')
-            echo "Instance Url is: $INSTANCE_URL + ' ' + succesfully authorised scratch org"
-            echo "${{ secrets.DEVHUB_KEY }}" > devhubkey.key
-      
-            # Check if Scratch Org exists
-            SCRATCH_EXISTS=$(sf org list --json | jq -r ".result.scratchOrgs[] | select(.username==\"$USERNAME\") | .username")
-            if [ -z "$SCRATCH_EXISTS" ]; then
+            echo "Instance Url is: $INSTANCE_URL"
+            echo "${{ secrets.DEVHUB_KEY }}" > devhubkey.key 
+            echo "Attempting to log into the scratch"
+            sf org login jwt --client-id $CONSUMER_KEY --jwt-key-file devhubkey.key --username $USERNAME --alias TestDeployScratch --instanceurl $INSTANCE_URL --set-default --json
+            if [ $? -eq 0 ]; then
+                echo "Login successful"
+            else
+                echo "Login failed"
                 # Create Scratch Org
                 echo "org does not exist, creating new"
                 output=$(sf org create scratch --definition-file config/project-scratch-def.json --alias TestDeployScratch --duration-days 10 --set-default --json | base64 -w 0)
@@ -63,10 +65,7 @@ jobs:
       
                 # Add or update secret
                 gh secret set SCRATC_ORG_AUTH --body=$(cat "result.json")
-            else
-                # Authorize into existing Scratch Org
-                echo "org already exists, logging into existing"
-                sf org login jwt --client-id $CONSUMER_KEY --jwt-key-file devhubkey.key --username $USERNAME --alias TestDeployScratch --instanceurl $INSTANCE_URL --set-default --json
+                exit 1
             fi
         env:
           GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
